import { SecretSanta } from "~/lib/store"

export const santas: readonly SecretSanta[] = [
  { state: "valid", name: "Hans" },
  { state: "valid", name: "Otto" },
  { state: "valid", name: "Oskar" },
  { state: "valid", name: "Nadine" },
  { state: "valid", name: "Nina" },
  { state: "valid", name: "Anita" },
  { state: "valid", name: "Petra" },
  { state: "valid", name: "Sandra" },
  { state: "valid", name: "Flavia" },
  { state: "valid", name: "Andrea" },
  { state: "valid", name: "Tina" },
  { state: "valid", name: "Rosina" },
  { state: "valid", name: "Kurt" },
  { state: "valid", name: "Berta" },
  { state: "valid", name: "Karl" },
  { state: "valid", name: "Boris" },
  { state: "valid", name: "Sven" },
  { state: "valid", name: "Carla" },
  { state: "valid", name: "Xenia" },
  { state: "valid", name: "Sonja" },
  { state: "valid", name: "Reto" },
  { state: "valid", name: "Thomas" },
  { state: "valid", name: "Daniel" },
  { state: "valid", name: "Peter" },
  { state: "valid", name: "Monika" },
  { state: "valid", name: "Heidi" },
  { state: "valid", name: "Jacqueline" },
]
